import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from './header'
import React from 'react'
import Mainloader from '../components/mainpage'

export default function Home() {

  return (
    <div >
    <div >
      <Head>
        <title>HelloHead</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Header />
</div><div><button>Shuffle deck</button></div>

      <main className={styles.main}>
        <Mainloader/>
      </main>
      <footer className={styles.footer}>
        <div>Hello Footer</div>
      </footer>
    </div>
  )
}
